python3 delete_ami_test.py peddler-test.peddler.com ap-south-1
python3 delete_ami_test.py lookeats-test.lookeats.com ap-south-1
python3 delete_ami_test.py logistech-test ap-south-1
python3 delete_ami_test.py socheat-test ap-south-1
python3 delete_ami_test.py delinet-test.delinet.com ap-south-1
python3 delete_ami_test.py infinityplumbing-test ap-south-1
python3 delete_ami_test.py bakerix-test.bakerix.com ap-south-1
python3 delete_ami_test.py rocket-dev.rocket.com ap-south-1
python3 delete_ami_test.py amrita-dev ap-south-1
python3 delete_ami_test.py infinityplumbing-test ap-south-1
python3 delete_ami_test.py rocket-dev.rocket.com ap-south-1
python3 delete_ami_test.py berhan-dev ap-south-1
python3 delete_ami_test.py sstires-test ap-south-1
python3 delete_ami_test.py gomeat-dev ap-south-1
python3 delete_ami_test.py delinet-dev.delinet.com ap-south-1
python3 delete_ami_test.py logistech-test-Ami ap-south-1
